[env]
CMAKE_C_FLAGS_RELEASE = "/MD /O2 /Ob2 /DNDEBUG"
CMAKE_CXX_FLAGS_RELEASE = "/MD /O2 /Ob2 /DNDEBUG /EHsc /utf-8"
GGML_NATIVE = "OFF"
GGML_AVX = "ON"
GGML_AVX2 = "ON"
GGML_FMA = "ON"
GGML_F16C = "ON"
LIBCLANG_PATH = { value = "tools/libclang", relative = true }
